### ISSUE TITLE
ERR Listening on remote endpoint for HTTPS failed

### ISSUE THREAD

**Issue by jesues-ar** [loophole/cli#252]
**Describe the bug**
INF Succeeded to accept connection over HTTPS
INF EOF Connection dropped, reconnecting...
Initializing secure tunnel...  Success!
ERR Listening on remote endpoint for HTTPS failed
FTL Tunnel startup error error=EOF tunnelId=5f2916f6-2506-4935-8e8b-ea649d1148d4

**Environment**
 - OS: windows10
 - Version :loophole-cli_1.0.0-beta.15_windows_64bit

**Comment by Morishiri** [comment]
Issue should be resolved.

**Comment by LWFlouisa** [comment]
Nope its still happening...a lot...this time every time I reboot my computer. This is untenable with every time Youtube deliberately hijacks my browser and slows it down.
